### ISSUE TITLE
Compilation error on master using MacOS

### ISSUE THREAD

**Issue by nmellado** [STORM-IRIT/Radium-Engine#628]
The last PR introduce a compilation error due to namespaces ambiguities:
https://github.com/STORM-IRIT/Radium-Releases/runs/1539840285?check_suite_focus=true#step:7:106

**Comment by MathiasPaulin** [comment]
Well, I do not understand the error. 
First, After modifying the file to fix the issue, when I compile on my machine (MacOs 10.14.6, AppleClang 10.0.1.10010046), all works fine.

BTW, the CI still stop with the following error at line 22 of file `..../StackTrace.cpp`. 

```
/Users/runner/work/Radium-Engine/Radium-Engine/src/Radium-Engine/src/Core/Utils/StackTrace.cpp:22:1: error: no type named 'string' in namespace 'Ra::Core::Utils::std'; did you mean '::std::string'?
std::string StackTrace( int skip ) {
^~~~~~~~~~~
::std::string
```
But at this line, there is no more this instruction. The file was updated but the CI still use an old one. What happens ? Why ?

@nmellado : is the source cached for the CI ?
