### ISSUE TITLE
Compilation error with pop_os! 21.10

### ISSUE THREAD

**Issue by Niwol** [STORM-IRIT/Radium-Engine#843]
Error message:

```
In file included from /usr/include/signal.h:328,
                 from /home/lowin/Documents/projects/univ/PentaCode/Radium-Engine/tests/external/Catch2/src/Catch2_download/single_include/catch2/catch.hpp:8031,
                 from /home/lowin/Documents/projects/univ/PentaCode/Radium-Engine/tests/unittest/unittest.cpp:2:
/home/lowin/Documents/projects/univ/PentaCode/Radium-Engine/tests/external/Catch2/src/Catch2_download/single_include/catch2/catch.hpp:10815:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
10815 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/sigstksz.h:24,
                 from /usr/include/signal.h:328,
                 from /home/lowin/Documents/projects/univ/PentaCode/Radium-Engine/tests/external/Catch2/src/Catch2_download/single_include/catch2/catch.hpp:8031,
                 from /home/lowin/Documents/projects/univ/PentaCode/Radium-Engine/tests/unittest/unittest.cpp:2:
/usr/include/unistd.h:640:17: note: ‘long int sysconf(int)’ declared here
  640 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
In file included from /home/lowin/Documents/projects/univ/PentaCode/Radium-Engine/tests/unittest/unittest.cpp:2:
/home/lowin/Documents/projects/univ/PentaCode/Radium-Engine/tests/external/Catch2/src/Catch2_download/single_include/catch2/catch.hpp:10874:45: error: size of array ‘altStackMem’ is not an integral constant-expression
10874 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
````

**Comment by nmellado** [comment]
Thanks for your report.
Can you please give use details about your configuration: operating system, compiler, cmake version.
Also, can you post the command you ran and the entire log ?

**Comment by MathiasPaulin** [comment]
system : pop_os! 21.10 (https://pop.system76.com/)
compiler : gcc 11.0.2
branch : release-candidate

This is strange because with the same compiler, release-candidate compiles fine on ubuntu 21.10 and debian 11 (Bullseye)

**Comment by dlyr** [comment]
Seems related to https://github.com/catchorg/Catch2/issues/2178

**Comment by dlyr** [comment]
Possible fix: edit 
`Radium-Engine/tests/external/CMakeLists.txt `
replace 
`external_download_now_git(Catch2 https://github.com/catchorg/Catch2.git v2.12.4)`
with 
`external_download_now_git(Catch2 https://github.com/catchorg/Catch2.git v2.13.8)`

**Comment by dlyr** [comment]
and as an alternative, you can disable tests during configuration with `-DRADIUM_ENABLE_TESTING=OFF`

**Comment by MathiasPaulin** [comment]
Sure, but this also disable demo apps. 
@Niwol could you test the solution proposed by @dlyr (update catch2) and tell us if this works.

**Comment by Niwol** [comment]
With this edit i could compile

**Comment by nmellado** [comment]
Thanks for the update.
We'll keep the issue open while it is not fixed in `release_candidate`.
